### PR TITLE
Updated icons and backgrounds

### PR DESCRIPTION
**Pull request by Skipper-is**
Separating this into stages! This is the background images, and YSCE icons, as well as an update to the scaling of non-tiled background images (that scale to screen)
Also updated wording to the about page, to include reference to YSCE, and YSFHQ. 
* Updated hawaii start points with Decaff's STPs for YSRP

### CODE REVIEW

**Comment by NodokaHanamura** [comment]
So just to be clear, this is good to merge with master now, or are you still working on this? Just want to make sure before I possibly futz it up again.

Also, we have a conflict regarding ys_timestamp.txt - I assume that's part of source, because I don't remember seeing that anywhere before in builds. Can we just nuke that or do we need to resolve it some other way?

**Comment by NodokaHanamura** [comment]
Saw your statements from the last PR and the PR in the libs repo - Other than the conflict we're good :D

**Review by NodokaHanamura — APPROVED** [review]

**Comment by Skipper-is** [comment]
Rebased to resolve conflicts.

**Comment by NodokaHanamura** [comment]
And merged. :)

**Pull request merged**
